/*
 * File: app/view/CarouselViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MatrimonyApp.view.CarouselViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.htmlcarousel',

    onContainerAfterRender: function(component, eOpts) {
        slideIndex = 1;
        showSlides = function(n) {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("dot");
            if (n > slides.length) {slideIndex = 1;}
            if (n < 1) {slideIndex = slides.length;}
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex-1].style.display = "block";
            dots[slideIndex-1].className += " active";
        };
        showSlides(slideIndex);
        // var prevButton= Ext.get('prevSlideButton');
        // var nextButton= Ext.get('nextSlideButton');
        var dotButton=  Ext.get('dotButton');
        // Next/previous controls
        // prevButton.on('click', function(slideIndex) {
        //   showSlides(slideIndex += 1);
        // }
        // );
        // // Thumbnail image controls
        // nextButton.on('click',function(n){
        //   showSlides(slideIndex+=-1);
        // });
        dotButton.on('click',function(n){
            showSlides(slideIndex = n.target.getAttribute('data-button-id'));
        });


    }

});
