/*
 * File: app/view/Carousel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MatrimonyApp.view.Carousel', {
    extend: 'Ext.container.Container',
    alias: 'widget.htmlCarousel',

    requires: [
        'MatrimonyApp.view.CarouselViewModel',
        'MatrimonyApp.view.CarouselViewController',
        'Ext.XTemplate'
    ],

    controller: 'htmlcarousel',
    viewModel: {
        type: 'htmlcarousel'
    },
    data: [
        {
            url: 'resources/images/img1.jpeg'
        },
        {
            url: 'resources/images/img2.jpeg'
        },
        {
            url: 'resources/images/img3.jpeg'
        }
    ],
    height: 500,
    tpl: [
        '<!-- Slideshow container -->',
        '<div class="slideshow-container">',
        '',
        '  <!-- Full-width images with number and caption text -->',
        '  <tpl for=".">',
        '  <div class="mySlides fade">',
        '      <img src="{url}" class="carousel-image">',
        '    <div class="text">Caption Text</div>',
        '  </div>',
        '  </tpl>',
        '  <!-- Next and previous buttons -->',
        '<!--   <a id="prevSlideButton" class="prev">&#10094;</a>',
        '  <a id="nextSlideButton" class="next">&#10095;</a> -->',
        '</div>',
        '<br>',
        '',
        '<!-- The dots/circles -->',
        '<div style="text-align:center">',
        '  <tpl for=".">',
        '  <span id="dotButton" data-button-id="{#}" class="dot"></span> ',
        '  </tpl>',
        '</div>'
    ],

    listeners: {
        afterrender: 'onContainerAfterRender'
    }

});