/*
 * File: app/view/HeaderPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MatrimonyApp.view.HeaderPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.headerpanel',

    requires: [
        'MatrimonyApp.view.HeaderPanelViewModel',
        'MatrimonyApp.view.HeaderPanelViewController',
        'Ext.form.Label',
        'Ext.container.Container',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'headerpanel',
    viewModel: {
        type: 'headerpanel'
    },
    border: false,
    itemId: 'HeaderPanel',
    bodyBorder: false,
    bodyCls: 'header',
    header: false,
    overlapHeader: false,
    title: 'MatrimonyApp',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'label',
            flex: 1,
            border: 2,
            cls: 'header-title',
            itemId: 'siteTitle',
            margin: 20,
            text: 'Matrimony App'
        },
        {
            xtype: 'container',
            margin: 5,
            defaults: {
                margin: 2
            },
            layout: 'table',
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'userName',
                    labelAlign: 'right',
                    emptyText: 'Username'
                },
                {
                    xtype: 'textfield',
                    itemId: 'password',
                    labelAlign: 'right',
                    labelClsExtra: 'header-label',
                    emptyText: 'Password'
                },
                {
                    xtype: 'button',
                    cls: 'login-button',
                    ui: 'loginbutton-small',
                    text: 'Login'
                },
                {
                    xtype: 'button',
                    cls: 'login-button',
                    ui: 'loginbutton-small',
                    text: 'Register',
                    listeners: {
                        click: 'onRegister'
                    }
                }
            ]
        }
    ]

});