/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MatrimonyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MatrimonyApp.view.MyViewportViewModel',
        'MatrimonyApp.view.HeaderPanel',
        'MatrimonyApp.view.MyPanel1',
        'MatrimonyApp.view.Carousel',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'myviewport'
    },
    layout: 'border',

    items: [
        {
            xtype: 'headerpanel',
            flex: 1,
            region: 'north'
        },
        {
            xtype: 'mypanel11',
            flex: 0.5,
            region: 'south'
        },
        {
            xtype: 'panel',
            flex: 8,
            region: 'center',
            itemId: 'MainPanel',
            frameHeader: false,
            header: false,
            title: 'My Panel',
            items: [
                {
                    xtype: 'htmlCarousel'
                }
            ]
        }
    ]

});