/*
 * File: app/view/RegistrationForm.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MatrimonyApp.view.RegistrationForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.registrationform',

    requires: [
        'MatrimonyApp.view.RegistrationFormViewModel',
        'MatrimonyApp.view.RegistrationFormViewController',
        'Ext.form.field.Display',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.form.field.TextArea',
        'Ext.form.field.File',
        'Ext.container.Container',
        'Ext.button.Button',
        'Ext.panel.Tool'
    ],

    controller: 'registrationform',
    viewModel: {
        type: 'registrationform'
    },
    modal: true,
    reference: 'form',
    floating: true,
    itemId: 'registrationForm',
    ui: 'green-panel',
    bodyPadding: 10,
    title: 'Register',

    items: [
        {
            xtype: 'displayfield',
            hidden: true,
            fieldLabel: 'ID',
            name: 'id'
        },
        {
            xtype: 'combobox',
            fieldLabel: 'Profile for',
            name: 'profileType',
            store: [
                'Myself',
                'Son',
                'Daughter',
                'Brother',
                'Sister',
                'Friend',
                'Relative'
            ]
        },
        {
            xtype: 'textfield',
            fieldLabel: 'Name',
            name: 'name',
            regex: /[A-Za-z]/,
            regexText: 'Only Alphabets allowed'
        },
        {
            xtype: 'numberfield',
            fieldLabel: 'Age',
            name: 'age',
            invalidText: 'Please enter valid age',
            maxValue: 60,
            minValue: 18
        },
        {
            xtype: 'textfield',
            fieldLabel: 'Contact',
            name: 'contactNumber',
            enforceMaxLength: true,
            maxLength: 10,
            regex: /\d{10}/,
            regexText: 'Enter a valid contact number'
        },
        {
            xtype: 'textfield',
            fieldLabel: 'Email',
            name: 'emailAddress',
            regex: /^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/,
            regexText: 'Enter a valid email address'
        },
        {
            xtype: 'combobox',
            fieldLabel: 'Gender',
            name: 'gender',
            store: [
                'Male',
                'Female'
            ]
        },
        {
            xtype: 'languageCombo',
            fieldLabel: 'Language',
            name: 'language'
        },
        {
            xtype: 'textareafield',
            width: 400,
            fieldLabel: 'Other Details',
            name: 'otherDetails'
        },
        {
            xtype: 'filefield',
            anchor: '100%',
            fieldLabel: 'Profile photo'
        },
        {
            xtype: 'textfield',
            fieldLabel: 'Password',
            inputType: 'password',
            regex: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,})/,
            regexText: 'The password must contain one Upper case, one lower case and one numeric character and should be maximum 8 characters'
        },
        {
            xtype: 'container',
            padding: 10,
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    formBind: true,
                    itemId: 'saveButton',
                    margin: '5 5 5 100',
                    ui: 'loginbutton-small',
                    text: 'Register Free',
                    listeners: {
                        click: 'onSave'
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    itemId: 'cancelButton',
                    margin: 5,
                    ui: 'loginbutton-small',
                    text: 'Cancel',
                    listeners: {
                        click: 'onCancel'
                    }
                }
            ]
        }
    ],
    tools: [
        {
            xtype: 'tool',
            itemId: 'registrationExit',
            type: 'close',
            listeners: {
                click: 'onRegistrationExitClick'
            }
        }
    ]

});