/*
 * File: app/model/User.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MatrimonyApp.model.User', {
    extend: 'Ext.data.Model',
    alias: 'model.user',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    fields: [
        {
            type: 'int',
            name: 'userId'
        },
        {
            name: 'name'
        },
        {
            name: 'age'
        },
        {
            name: 'gender'
        },
        {
            type: 'string',
            name: 'otherDetails'
        },
        {
            name: 'profilePhoto'
        },
        {
            name: 'contactNumber'
        },
        {
            name: 'emailAddress'
        },
        {
            name: 'religion'
        },
        {
            name: 'language'
        }
    ],

    proxy: {
        type: 'rest',
        url: '/user/register',
        reader: {
            type: 'json',
            messageProperty: 'message',
            rootProperty: 'data'
        }
    }
});