/* auto generated by architect */ 
Ext.theme.addManifest([
    {
        "ui": "green-panel",
        "xtype": "panel"
    },
    {
        "ui": "untitled-ui-3",
        "xtype": "textfield"
    },
    {
        "ui": "loginbutton",
        "xtype": "button"
    }
]);